### ISSUE TITLE
Minecraft 1.12 port

### ISSUE THREAD

**Issue by Robijnvogel** [zsawyer/MumbleLink#15]
Just dropping this here as a ping and as a placeholder.
I may give this a shot myself, but I can not update the MC forum thread or CurseForge, so...

**Comment by magneticflux-** [comment]
It should be extremely easy to do, since 1.11 and 1.12 are very similar. Updating the Forge version and mappings in the `build.gradle` file and then running `build` should do the trick unless they're doing something weird with Forge.

**Comment by Robijnvogel** [comment]
@magneticflux if you could do so, I would be extremely grateful as I won't have access to my computer the next few days.
Still, we need Zsawyer to publish an official build. :)

**Comment by magneticflux-** [comment]
@Robijnvogel I'm currently fixing some compilation errors. I'll detail them here so that @zsawyer can have some warning about what they'll need to fix for 1.12.
- Fields in the `Minecraft` class have changed from `theWorld` to `world`
- Fields in the `Minecraft` class have changed from `thePlayer` to `player`
- Fields in the `Vec3d` class have changed from `x/y/zCoord` to `x/y/z`

**Comment by magneticflux-** [comment]
@Robijnvogel I have a jar file that launches Minecraft, but I don't have a Murmur server to test on yet. Do you want me to email it to you?

EDIT: Set up Mumble and Murmur; everything looks good so far.

**Comment by zsawyer** [comment]
Thank you guys for looking into this. I will see to pushing this update as soon as I have some time for it. Good job!

**Comment by Robijnvogel** [comment]
@zsawyer I think you might have forgotten about us. :P

**Comment by zsawyer** [comment]
Sorry for neglecting. I am having technical issues which take extra time to resolve ... which I didn't have. Life...

**Comment by Robijnvogel** [comment]
@zsawyer I sent you a PM on the MC Forums.

**Comment by sanchosk** [comment]
Does this mean that when 1.12 will be supported, the 1.12.2 version will work, too?
Or is there additional development needed?

**Comment by magneticflux-** [comment]
@sanchosk See my comment here: https://github.com/zsawyer/MumbleLink/pull/16#issuecomment-348844403

**Comment by sanchosk** [comment]
@magneticflux- Thanks! Will try to build it tomorrow :)

**Comment by Robijnvogel** [comment]
I updated the source and built it. Tomorrow, I am going to test it.

**Comment by Robijnvogel** [comment]
It seems to work with Mumble, but I did not get it to work with CrossTalk.
Uploading built file to Curse now. :)

**Comment by magneticflux-** [comment]
@Robijnvogel Are you sure everything is set up correctly on your end for CrossTalk? I read up a little and it seems to use the exact same method of getting data as Mumble does so that it can benefit from games already supporting Mumble.

**Comment by Robijnvogel** [comment]
I'll close this issue now, since, as you, @magneticflux- , pointed out, since both Mumble and Crosstalk use the same Link API, it should be working just as well on Teamspeak as on Mumble.

And if there is actually an issue with Crosstalk, then we'll have to assume that that is caused by a problem in the interaction between Teamspeak and the Link API, which falls outside the scope of this mod.
