### ISSUE TITLE
Extra Temp folders being created

### ISSUE THREAD

**Issue by magneticflux-** [zsawyer/MumbleLink#17]
Every time a DLL is loaded, a new temp file is created and never removed. I now have several dozen folders called `MumbleLink7060520309212793916native`. A similar problem occured on another project I worked on: andrew-hoffman/halfnes/issues/37

**Comment by zsawyer** [comment]
This has to do with how JNA unpacks the native libraries. I would assume it doesn't use the [deleteOnExit](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#deleteOnExit--) or this is unreliable (maybe the normal Minecraft shutdown is not considered a _normal termination of the virtual machine_.

Is this issue still existent on normal MC exits?

**Comment by magneticflux-** [comment]
Sorry, I don't have information on this anymore and I primarily use Fabric now. I did some work on extracting temp files [here](https://github.com/magneticflux-/classpath-resource-extractor) to use [here](https://github.com/magneticflux-/ortools-java) that might help if it comes up in the future again though.
