### ISSUE TITLE
[Feature] Discord Gamebridge positional audio compatibility

### ISSUE THREAD

**Issue by Robijnvogel** [zsawyer/MumbleLink#19]
Discord is developing positional audio.
To get in on the action early, see [this](https://discordia.me/gamebridge).

This issue is a placeholder to not forget this until they get that far.

**Comment by Robijnvogel** [comment]
It seems like it will not be possible to use Discord Gamebridge for this in the foreseeable future:
https://www.reddit.com/r/discordapp/comments/7t0jyl/gamebridge_dead_or_when/

However it may be possible to use Rich Presence to directly set the volume and pan of other users in the same audio channel.
https://news.ycombinator.com/item?id=13981914
https://discordapp.com/developers/docs/topics/rpc#setuservoicesettings

How would we determine which Discord user-id belongs to which MC client? Probably a server-sided mod.

**Comment by Robijnvogel** [comment]
Apparently this volume and panning isn't on a per-client-basis, but rather affects a user's volume and panning for everyone in the voice channel. :/
Source: Asie

**Comment by zsawyer** [comment]
It won't happen:

From Sept 29. 2019; Discord GameSDK Help; #game-sdk

> <@53908232506183680> any info on Positional Audio being reintroduced?
@DutchAndDangerous#2296  

> <@225595810115485697> no, the extent to which we support positional audio is with the pan and volume abilities. As a general philosophy, we don't want our voice chat to be like Vivox. With a solution like Vivox, you can do positional audio, filters to sound like you're in a cave, underwater, etc. If that's what you absolutely need, something like Vivox would be your best choice.
> 
> We aim to make sure that Discord audio quality is as amazing as it can be, so we don't want a lot of mutating with the sound outside of pan and audio.
@Mason#1337
