### ISSUE TITLE
Muting non linked users

### ISSUE THREAD

**Issue by Jorgen1040** [zsawyer/MumbleLink#21]
Would it be possible to mute non linked users to stop them from listening and/or talking to all the players ingame? 
It can get annoying when people dont follow the rules and join the game channel without linking to Minecraft first.

**Comment by magneticflux-** [comment]
That's an issue to take up with Mumble; there's no support for voice segregation in the Link plugin.

Source: https://wiki.mumble.info/wiki/Link#Context
> If context between two Mumble users does not match the positional audio the data is stripped server-side and voice will be received as non-positional.

Also if you're interested in a 1.14 version there's mine here: https://github.com/magneticflux-/fabric-mumblelink-mod

**Comment by zsawyer** [comment]
Nothing we can do. 
This needs to be handled by the mumble client or the murmur server. 
Usually the non-linked users get muted, deafned, and are moved to a different channel through some kind of server script (see [mumo](https://wiki.mumble.info/wiki/Mumo)).
