### ISSUE TITLE
travis ci build stopped working

### ISSUE THREAD

**Issue by zsawyer** [zsawyer/MumbleLink#22]
since JDK8 has gone commercial at Oracle we need to figure out which license or version of JDK we need to use

```
Installing oraclejdk8
164
$ export JAVA_HOME=~/oraclejdk8
165
$ export PATH="$JAVA_HOME/bin:$PATH"
166
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
167
Ignoring license option: BCL -- using GPLv2+CE by default
168
install-jdk.sh 2019-07-17
169
Expected feature release number in range of 9 to 14, but got: 8
170
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```

**Comment by magneticflux-** [comment]
I've found `openjdk8` works well if you still need Java 1.8. Anything works for Java 9+ though.

Edit: So does this mean the Forge mod devs are coming out of hibernation now that Forge has a working 1.14 release? If you haven't been keeping up, make sure you check out FabricMC.

**Comment by zsawyer** [comment]
> I've found openjdk8 works well if you still need Java 1.8. Anything works for Java 9+ though.

alright I applied it and it seems to work :)
please check #23


> Edit: So does this mean the Forge mod devs are coming out of hibernation now that Forge has a working 1.14 release? If you haven't been keeping up, make sure you check out FabricMC.

I don't know. I just tried to build HEAD and it failed.

**Comment by zsawyer** [comment]
seems fixed https://travis-ci.org/zsawyer/MumbleLink/builds/582967343
