### ISSUE TITLE
pre-release 1.15.2 version sided_setup error on launch with forge 1.15.2-31.1.48

### ISSUE THREAD

**Issue by jdudetv** [zsawyer/MumbleLink#27]
![image](https://user-images.githubusercontent.com/51935420/80308177-c2f65800-8810-11ea-8e07-65569eba0884.png)

**Comment by zsawyer** [comment]
thanks for the bug report. this should be fixed in the actual release now. 
https://github.com/zsawyer/MumbleLink/releases/tag/4.4.1

note: I have deleted the pre-release as it was unstable.
