### ISSUE TITLE
Instructions for use with the Minecraft Flatpak

### ISSUE THREAD

**Issue by devurandom** [zsawyer/MumbleLink#30]
I am running a vanilla Minecraft server version 1.15.2. On the client I run Minecraft 1.15.2, Minecraft Forge 31.2.0, MumbleLink for Forge 4.4.1, ExtendedPASupport for MumbleLink 1.1.0 (according to the "Mods" menu in the Minecraft client's main menu). The client runs in Flatpak 1.6.3.

Without any modifications MumbleLink will not work: no Minecraft linked" message in Mumble and no "Mumble linked" message in Minecraft.

I need to give additional permissions to the Minecraft Flatpak by running `flatpak override --user --device=shm com.mojang.Minecraft` on the command line (and possibly restart the Minecraft Flatpak if it was already running) to make the link work. (Reason: The Mumble Link works via SHM and `/dev/shm` is by default sandboxed by Flatpak.)

It would be nice if this information could be added to the FAQ / Troubleshooting section in the MumbleLink readme.

**Comment by zsawyer** [comment]
Thank you for this valuable feedback. I am also glad that you were able to figure out the problem and find a solution. 
I believe /dev/shm is a given by Mumble's Link Plugin so all we can do is properly document your solution.
