### ISSUE TITLE
1.16.4 Forge support

### ISSUE THREAD

**Issue by ced455** [zsawyer/MumbleLink#34]
Hello,

Me and my friend would love to use this mod on our server.

if you need anyone to test feel free to contact me.

**Comment by zsawyer** [comment]
closed by 6a49699

**Comment by zsawyer** [comment]
closed by 547675840cf6df3def680fb243fb245143905345, 6a4969930fb8e0d834ebe4cf984d1348ad7d8644

https://github.com/zsawyer/MumbleLink/releases/tag/4.6.1 is actually compatible with 1.16.4
