### ISSUE TITLE
1.16.5 - Not fully functioning

### ISSUE THREAD

**Issue by elkinsa** [zsawyer/MumbleLink#36]
Might just be me being new to Mumble, but I am trying the 1.16.5 release and positional audio is working, but not distance. I have positional audio and link to game and transmit position checked in Mumble.

**Comment by elkinsa** [comment]
As a note I cannot find Forge logs (though I do have it and am running it), but I do see other logs saying Mumble linked but I do not see it in chat on the server.

**Comment by elkinsa** [comment]
Ah realized it was not setting minimum distance.

**Comment by zsawyer** [comment]
> As a note I cannot find Forge logs (though I do have it and am running it), but I do see other logs saying Mumble linked but I do not see it in chat on the server.

It seems to prompt the text while you are loading in. If this takes a bit of time the chat message will not "show anymore". You should be able to see it in the chat log. Simply try typing a message and it should show. 

It's always a good idea to check the Mumble client too. 

I use the start up option in the Minecraft launcher to get log details while the game is running.

**Comment by zsawyer** [comment]
> 
> 
> Ah realized it was not setting minimum distance.

Thanks for posting your solution!
