### ISSUE TITLE
mumble link not working

### ISSUE THREAD

**Issue by cordlessblues** [zsawyer/MumbleLink#44]
i have mumble link mod installed in mumble it says Minecraft linked  but I see no mumble linked in the Minecraft chat here are my logs
[latest.log](https://github.com/zsawyer/MumbleLink/files/6251657/latest.log)
me and my freinds hear eachother but the postinal part is not working

**Comment by Robijnvogel** [comment]
It says "Mumble linked" in your log though:
`[18:59:31] [Thread-10/INFO]: [CHAT] Mumble linked.`

As for positional audio not working, there can be many reasons for that.
Do you and your friends all use the same version of MumbleLink for MC Forge and is it working correctly for all of you?
If so, what are your positional audio settings in Mumble itself?

**Comment by zsawyer** [comment]
Assume fixed by setting up mumble correctly as instructed in readme.
