### ISSUE TITLE
Positional Audio Doesn't Function At All

### ISSUE THREAD

**Issue by TrikiNya** [zsawyer/MumbleLink#45]
One day I tried using Mumblelink with my friend. I had Fabric while she had Forge. It didn't work because [this is still an issue that needs fixing.](https://github.com/magneticflux-/fabric-mumblelink-mod/issues/61) Yesterday I used the Forge version she used the day before. Same problem occurred. Positional audio did not work.
I believe this might have something to do with the order in which I joined the things. I joined the mumble server first, then the Minecraft server. The mod didn't seem to link when I found out the issue. Is that the problem? Do I need to join in a specific order for it to work?

Note: I can't give you Mumble logs

**Comment by zsawyer** [comment]
The order should not matter. Though I usually start mumble first (like you did) during testing. 

Without more details this is impossible to troubleshoot. 

Thanks for the feedback on #61
