### ISSUE TITLE
Positional audio is not working

### ISSUE THREAD

**Issue by DustinReturns** [zsawyer/MumbleLink#48]
So my friends and I have encountered a big problem with this mod. We can't use positional audio even though we turned everything on that tutorials told us to. We can hear each other through Mumble but the positional audio simply doesn't work at all. It even says that it is linked to Minecraft, so we don't know what the problem is. We even played around with the minimum distance, volume etc. and nothing worked. We're using a 1.16.5 forge server (we didn't upload the mod onto the server, so yes we know that it's client-sided) with a mod pack that enhances vanilla only slightly, so there aren't many major changes that may or may not cause an issue with the positional audio of mumble.

We were around 5 people and it didn't work at all for any of us.

**Comment by zsawyer** [comment]
Can you please provide which versions you are using exactly? So that I can try to reproduce this:
Operating System
Mumble
Link Plugin 
Minecraft
Forge
MumbleLink

**Comment by zsawyer** [comment]
closing since no response
