### ISSUE TITLE
1.17 compatibility?

### ISSUE THREAD

**Issue by meowphetamine** [zsawyer/MumbleLink#49]
Not sure where to contact you.

I was planning on supporting mumblelink on my 1.17 java server and was wondering if it was going to be updated.

**Comment by zsawyer** [comment]
This is the correct way to contact us. Yes there will be an update. 
Though I cannot tell you when, yet.

**Comment by djeel** [comment]
plsss add 1.17.1 :'(

**Comment by zsawyer** [comment]
@Djeel please give this a try:
https://github.com/zsawyer/MumbleLink/releases/tag/1.17.1-5.1.0
