### ISSUE TITLE
1.12.2 Source

### ISSUE THREAD

**Issue by GlobalHive** [zsawyer/MumbleLink#50]
Is it possible to get the 1.12.2 source ?
I know its an old version, but my server still uses many mods of 1.12.2

And i would like to implement a GUI which tells the client to login to the murmur server if they are not connected already...

**Comment by Robijnvogel** [comment]
It seems like we have no leftover branch with that version of the source, but I believe that this pull request was the first and only commit for MC 1.12
https://github.com/zsawyer/MumbleLink/commit/db19c05901b08dddc6eedaa08409fc1a26834531

**Comment by GlobalHive** [comment]
Okay thank you :D

**Comment by zsawyer** [comment]
You can find the sources in the Release section: 
https://github.com/zsawyer/MumbleLink/releases/tag/4.2.6

Tag 4.2.6 (80ae79b1b89530db22ac030e93acccf453a90bf1) this is probably the code base you should be using.
