### ISSUE TITLE
mumblelink fails to work with mumble 1.4.x

### ISSUE THREAD

**Issue by cjunekim** [zsawyer/MumbleLink#56]
Hello

I've been using mumblelink successfully with mumble's official releases such as 1.3.3 and 1.3.4. However, mumblelink fails to work with mumble 1.4.x snapshots. I see the minecraft linked and mumble linked message on mumble and minecraft, but it doesn't do positional audio.

There has been a report on the compatibility issue with 1.4.x snapshots on fabric-mumblelink-mod page. https://github.com/magneticflux-/fabric-mumblelink-mod/issues/73

The versions that I am using are:

Minecraft 1.15.2
Forge 31.2.0
MumbleLink 1.15.2-4.4.1
Mumble client mumble_client-1.4.0_2021-09-04_g37ee67716_snapshot.x64

**Comment by cjunekim** [comment]
Maybe this is related. https://github.com/mumble-voip/mumble/issues/5217

**Comment by zsawyer** [comment]
Yes, this was a Mumble issue which is fixed, now.
