### ISSUE TITLE
Proximity chat on minecraft doesn't seem to work

### ISSUE THREAD

**Issue by Reyxem** [zsawyer/MumbleLink#57]
Hey,
I know this has been already asked too many times but I couldn't find any answer. So yesterday I installed mumble on the official website (version 1.3.4), MumbleLink on Curseforge (last version for 1.17.1), and, of course, Minecraft 1.17.1. For the mod part, I just slid it into my mod folder and did nothing afterward with it. My Minecraft only has one mod, optifine. For the mumble part, here are some screens of what I did with a friend:

![Mumble 1](https://user-images.githubusercontent.com/94697590/142641998-309cc2bb-4e27-4b91-bdf0-f62e8d0ce8e2.PNG)
![Mumble 2](https://user-images.githubusercontent.com/94697590/142642001-9b25065b-d21f-4cf3-b399-ae75d701faa0.PNG)
![Mumble 3](https://user-images.githubusercontent.com/94697590/142642002-0eb77c01-268d-4d61-afc7-b7c6d303089f.PNG)

We also changed the peripherical thing used for the audio input and output but it didn't change anything, we can hear each other but it's as if we were on discord, no proximity chat.
Thanks for taking the time to help me,
Reyxem

**Comment by zsawyer** [comment]
Your mumble settings all look fine. Can you please post your Minecraft logs? I would presume that either the mod does not get loaded properly or the linking between the mod and mumble fails.

**Comment by zsawyer** [comment]
timed out
