### ISSUE TITLE
MumbleLinkImpl issue

### ISSUE THREAD

**Issue by alankasprzyk23** [zsawyer/MumbleLink#59]
-- MOD mumblelink --
Details:
	Mod File: mumblelink-1.16.5-5.0.0.jar
	Failure message: MumbleLink for Forge has class loading errors
		java.lang.RuntimeException: Attempted to load class zsawyer/mods/mumblelink/MumbleLinkImpl for invalid dist DEDICATED_SERVER
	Mod Version: 5.0.0
	Mod Issue URL: https://github.com/zsawyer/MumbleLink/issues
	Exception message: java.lang.RuntimeException: Attempted to load class zsawyer/mods/mumblelink/MumbleLinkImpl for invalid dist DEDICATED_SERVER

**Comment by zsawyer** [comment]
You are trying to run the client-side only mod on a Minecraft server. It doesn't work like that. You need a separate Mumble server ("Murmur").
